name: code-editor-ui Image CI

on:
  push:
    branches:
      - main
    paths:
      - "code-editor-online/openerp-code-editor-client/**"

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      #     - name: Build the Docker image
      #       run: docker build . --file Dockerfile --tag lms-ui:$(date +%s)
      - name: Create file .env
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: ".env"
          fileDir: "./code-editor-online/openerp-code-editor-client/"
          encodedString: ${{ secrets.CODE_EDITOR_UI_B64_SECRET }}
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: leanhtuan/code-editor-ui
          #         tags: v1, latest
          directory: "code-editor-online/openerp-code-editor-client/"
          registry: docker.io
          dockerfile: "code-editor-online/openerp-code-editor-client/Dockerfile"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          addLatest: true
      #        addTimestamp: true
      - name: Remove config file
        uses: JesseTG/rm@v1.0.2
        with:
          path: "./code-editor-online/openerp-code-editor-client/.env"
