name: code-editor Image CI

on:
  push:
    branches:
      - main
    paths:
      - "code-editor-online/openerp-code-editor-server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - name: Create file appication.yml
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: "application.yml"
          fileDir: "./code-editor-online/openerp-code-editor-server/src/main/resources/"
          encodedString: ${{ secrets.CODE_EDITOR_B64_SECRET }}
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: leanhtuan/code-editor
          directory: "code-editor-online/openerp-code-editor-server/"
          registry: docker.io
          dockerfile: "code-editor-online/openerp-code-editor-server/Dockerfile"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          addLatest: true
      - name: Remove config file
        uses: JesseTG/rm@v1.0.2
        with:
          path: "./code-editor-online/openerp-code-editor-server/src/main/resources/application.yml"
