name: task-managment Image CI

on:
  push:
    branches:
      - main
    paths:
      - "task-management/task-managment-backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Construct tag
        id: construct-tag
        run: |
          TAG_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')-${{ github.sha }}
          echo "::set-output name=TAG_NAME::$TAG_NAME"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./task-management/task-managment-backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/task-managment:${{ steps.construct-tag.outputs.TAG_NAME }}
            ${{ secrets.DOCKER_USERNAME }}/task-managment:latest
          cache-from: type=gha,scope=$GITHUB_REF_NAME-task-managment
          cache-to: type=gha,mode=max,scope=$GITHUB_REF_NAME-task-managment
