name: container-transport Image CI

on:
  push:
    branches:
      - main
    paths:
      - "containertransport/back_end/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - name: Create file appication.yml
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: "application.yml"
          fileDir: "./containertransport/back_end/src/main/resources/"
          encodedString: ${{ secrets.CONTAINER_TRANSPORT_B64_SECRET }}
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: leanhtuan/container-transport
          directory: "containertransport/back_end/"
          registry: docker.io
          dockerfile: "containertransport/back_end/Dockerfile"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          addLatest: true
      - name: Remove config file
        uses: JesseTG/rm@v1.0.2
        with:
          path: "./containertransport/back_end/src/main/resources/application.yml"
